SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';
SET @old_autocommit=@@autocommit;

USE shop;

SET AUTOCOMMIT=0;

INSERT INTO product (product_id, name, price) VALUES
(1, 'Tシャツ', 5800),
(2, 'パーカー', 12800),
(3, 'キャップ', 4800);
COMMIT;